### PR TITLE
add server alias/virtual host methods to interop

### PR DESCRIPTION
**Pull request by gregoryyoung**
Looking at adding further support but even having the defines is probably useful.

I think we will be doing http prefixes through these

### CODE REVIEW

**Comment by kekekeks** [comment]
That's not how it works. That's not how any of this works.
1) `string` args won't be marshaled properly without [MarshalAs(UnmanagedType.LPStr)] applied
2) you need to name delegates *exactly* as in libevent, i. e. not `ev_remove_server_aliad`, but `evhttp_remove_server_alias` (custom binding magic won't find entry points otherwise)
3) you need to add a static variable somewhere [here](https://github.com/gregoryyoung/evhttp-sharp/blob/master/EvHttpSharp/Interop/Event.cs#L200)
4) `delegate int ev_add_virtual_host(EvHttp http, string pattern, EvHttp host);` - 
- `host` should be `out` parameter
- it's better to use `out IntPtr` and add a custom constructor for `EvHttp`, so it won't claim ownership over the handle. [EvHttp](https://github.com/gregoryyoung/evhttp-sharp/blob/master/EvHttpSharp/Interop/EvHttp.cs#L14) is a `SafeHandle` which is `CriticalFinalizerObject` and `Dispose` is guaranteed to be called on GC thread and it will call `ReleaseHandle` and then we'll have a big bada boom.


Also, take a look on [this](https://github.com/kekekeks/prowingen). I'm trying to wrap Facebook's proxygen HTTP stack, but got stuck because
- I got a lot of other work to do last month 
- they don't merge my pull request with websocket support

**Comment by gregoryyoung** [comment]
2) you need to name delegates *exactly* as in libevent, i. e. not
ev_remove_server_aliad, but evhttp_remove_server_alias(custom binding magic
won't find entry points otherwise)

There is a commit fixing this already (from about an hour ago)

On Mon, Mar 9, 2015 at 10:38 PM, Nikita Tsukanov <notifications@github.com>
wrote:

> That's not how it works. That's not how any of this works.
> 1) string args won't be marshaled properly without
> [MarshalAs(UnmanagedType.LPStr)] applied
> 2) you need to name delegates *exactly* as in libevent, i. e. not
> ev_remove_server_aliad, but evhttp_remove_server_alias (custom binding
> magic won't find entry points otherwise)
> 3) you need to add a static variable somewhere here
> <https://github.com/gregoryyoung/evhttp-sharp/blob/master/EvHttpSharp/Interop/Event.cs#L200>
> 4) delegate int ev_add_virtual_host(EvHttp http, string pattern, EvHttp
> host); -
>
>    - host should be out parameter
>    - it's better to use out IntPtr and add a custom constructor for EvHttp,
>    so it won't claim ownership over the handle. EvHttp
>    <https://github.com/gregoryyoung/evhttp-sharp/blob/master/EvHttpSharp/Interop/EvHttp.cs#L14>
>    is a SafeHandle which is CriticalFinalizerObject and Dispose is
>    guaranteed to be called on GC thread and it will call ReleaseHandle
>    and then we'll have a big bada boom.
>
> Also, take a look on this <https://github.com/kekekeks/prowingen>. I'm
> trying to wrap Facebook's proxygen HTTP stack, but got stuck because
>
>    - I got a lot of other work to do last month
>    - they don't merge my pull request with websocket support
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kekekeks/evhttp-sharp/pull/17#issuecomment-77937043>.
>



-- 
Studying for the Turing test

**Comment by kekekeks** [comment]
You've fixed the typo, not the prefix (`ev_` - `evhttp_`)

**Comment by kekekeks** [comment]
http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/http_8h.html#a6b2b581793f361f68fd21cff110aa262

**Comment by gregoryyoung** [comment]
yes fixing the rest right now

On Mon, Mar 9, 2015 at 10:56 PM, Nikita Tsukanov <notifications@github.com>
wrote:

> You've fixed the typo, not the prefix (ev_ - evhttp_)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kekekeks/evhttp-sharp/pull/17#issuecomment-77940733>.
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Should be better now.

Cheers,

Greg

On Mon, Mar 9, 2015 at 10:59 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> yes fixing the rest right now
>
> On Mon, Mar 9, 2015 at 10:56 PM, Nikita Tsukanov <notifications@github.com
> > wrote:
>
>> You've fixed the typo, not the prefix (ev_ - evhttp_)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kekekeks/evhttp-sharp/pull/17#issuecomment-77940733>.
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Pull request merged**
